import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar/Navbar";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex ">
          <div className=" h-full sticky top-0 border-[#767676] border-r-[1.5px]  ">
            <Navbar />
          </div>
          <div className=" ">
          {children}
          </div>
        
        </div>
      </body>
    </html>
  );
}
