import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar/Navbar";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <style>
          {`
            @media only screen and (max-width: 500px){
              .main-container{
                display:flex;
                flex-direction:;
                justify-content:center;
                align-items:center;
              }
              Navbar{
                display:none;
              }
              
            }
          `}
        </style>

        <div className="main-container h-screen w-full flex justify-center items-center">
          <Navbar className="nav sm:hidden"/>
          <div className="content h-full w-full overflow-y-scroll">
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}
