import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar/Navbar";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className=" flex ">
          <div className=" h-full sticky top-0 border-[#767676] border-r-[1.5px]  ">
            <Navbar />
          </div>
          
          <div className=" ">
          <div className=" bg-[#1E1F24] p-5 border-[#767676] border-b-[1.5px] mb-5 sticky top-0">
        <p className="text-[#00B2FF] text-3xl font-semibold p-2">Page Name</p>
      </div>
          {children}
          </div>
        
        </div>
      </body>
    </html>
  );
}
